spring:
    profiles:
        active:
            - dev
    application:
        name: ticketsystem
server:
    port: 8080

---
spring:
    config:
        activate:
            on-profile:
                - prod
    data:
        mongodb:
            host: localhost
            port: 27017
            database: ticketsystemdb


---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        name: ticketsystemtestdb
        generate-unique-name: false
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
    

        